name: Ebenezer CI
run-name: Running test and check vulnerabilities in [${{ github.ref_name }}] by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_ENV: test

permissions:
  contents: read

jobs:
  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24'

      - name: Get packages
        shell: bash
        run: |
          go mod download
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Vulncheck
        shell: bash
        run: govulncheck ./...

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24'

      - name: Get packages
        shell: bash
        run: |
          go mod download
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run Test
        shell: bash
        run: make test-ci